language: node_js
rvm:
  - 2.3.3
node_js: 
  - "7.3"

before_install:
  - rvm install 2.3

install:
  - npm install -g firebase-tools

before_script:
 - chmod +x ./script/cibuild # or do this locally and commit

script: ./script/cibuild

after_success:
  -  firebase deploy --token 

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false # route your build to the container-based infrastructure for a faster build

deploy:
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN