language: ruby
rvm:
  - 2.3.3
# node_js: 
#   - "7.3"
# script:
#   - echo "run test"
# install:
#   - npm install -g firebase-tools
# after_success:
#   -  firebase deploy --token 

before_script:
 - chmod +x ./script/cibuild # or do this locally and commit

script: ./script/cibuild

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false # route your build to the container-based infrastructure for a faster build

deploy:
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN