title: Prodesk
name: Prodesk Life
email: hello@prodesk.life
description: Standup for right reasons, Prodesk is a Height adjustable standing desk which work for you. Prodesk is easy to setup. Prodesk is avaliable for buying in India
keywords: Height ajustable, standing desk, healthly, india, Standing desk in India, Buy standing desk in bangalore


social:
  dribbble:
  email: hello@prodesk.life
  facebook: prodesklife
  flickr:
  linkedin:
  rss: # just type anything here for a working RSS icon
  twitter: Prodesk_life
  phone: +91-9020660884
  location: Bangalore, India
  googleplus: # anything in your profile username that comes after plus.google.com/

fb_app_id: 798530620306323
google_analytics: UA-60526867-2

url: https://prodesk.life/
baseurl: ""

permalink: /:title/
version: v3.5.0
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

sass:
  sass_dir: _sass
  sourcemap: true
  style: :compressed

include: ["_pages"]

plugins:
  # - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - functions
  - firebase.json
  - emails

assets:
  autoprefixer:
    browsers: ["last 2 versions","> 5%","IE 9"]